# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asset.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sensu.types.Asset" do
    optional :name, :string, 1
    optional :url, :string, 2
    optional :sha512, :string, 3
    map :metadata, :string, :string, 4
    repeated :filters, :string, 5
    optional :organization, :string, 6
  end
end

module Sensu
  module Types
    Asset = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.Asset").msgclass
  end
end
