# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: check.proto

require 'google/protobuf'

require_relative 'asset_pb'
require_relative 'hook_pb'
require_relative 'time_window_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sensu.types.CheckRequest" do
    optional :config, :message, 1, "sensu.types.CheckConfig"
    repeated :assets, :message, 2, "sensu.types.Asset"
    repeated :hooks, :message, 3, "sensu.types.HookConfig"
  end
  add_message "sensu.types.ProxyRequests" do
    repeated :entity_attributes, :string, 1
    optional :splay, :bool, 2
    optional :splay_coverage, :uint32, 3
  end
  add_message "sensu.types.CheckConfig" do
    optional :command, :string, 1
    optional :environment, :string, 2
    repeated :handlers, :string, 3
    optional :high_flap_threshold, :uint32, 4
    optional :interval, :uint32, 5
    optional :low_flap_threshold, :uint32, 6
    optional :name, :string, 7
    optional :organization, :string, 8
    optional :publish, :bool, 9
    repeated :runtime_assets, :string, 10
    repeated :subscriptions, :string, 11
    optional :ExtendedAttributes, :bytes, 12
    optional :proxy_entity_id, :string, 13
    repeated :check_hooks, :message, 14, "sensu.types.HookList"
    optional :stdin, :bool, 15
    optional :subdue, :message, 16, "sensu.types.TimeWindowWhen"
    optional :cron, :string, 17
    optional :ttl, :int64, 18
    optional :timeout, :uint32, 19
    optional :proxy_requests, :message, 20, "sensu.types.ProxyRequests"
    optional :round_robin, :bool, 21
  end
  add_message "sensu.types.Check" do
    optional :command, :string, 1
    optional :environment, :string, 2
    repeated :handlers, :string, 3
    optional :high_flap_threshold, :uint32, 4
    optional :interval, :uint32, 5
    optional :low_flap_threshold, :uint32, 6
    optional :name, :string, 7
    optional :organization, :string, 8
    optional :publish, :bool, 9
    repeated :runtime_assets, :string, 10
    repeated :subscriptions, :string, 11
    optional :proxy_entity_id, :string, 13
    repeated :check_hooks, :message, 14, "sensu.types.HookList"
    optional :stdin, :bool, 15
    optional :subdue, :message, 16, "sensu.types.TimeWindowWhen"
    optional :cron, :string, 17
    optional :ttl, :int64, 18
    optional :timeout, :uint32, 19
    optional :proxy_requests, :message, 20, "sensu.types.ProxyRequests"
    optional :round_robin, :bool, 21
    optional :duration, :double, 22
    optional :executed, :int64, 23
    repeated :history, :message, 24, "sensu.types.CheckHistory"
    optional :issued, :int64, 25
    optional :output, :string, 26
    optional :state, :string, 27
    optional :status, :uint32, 28
    optional :total_state_change, :uint32, 29
    optional :last_ok, :int64, 30
    optional :occurrences, :int64, 31
    optional :occurrences_watermark, :int64, 32
    repeated :silenced, :string, 33
    repeated :hooks, :message, 34, "sensu.types.Hook"
    optional :ExtendedAttributes, :bytes, 99
  end
  add_message "sensu.types.CheckHistory" do
    optional :status, :uint32, 1
    optional :executed, :int64, 2
  end
end

module Sensu
  module Types
    CheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.CheckRequest").msgclass
    ProxyRequests = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.ProxyRequests").msgclass
    CheckConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.CheckConfig").msgclass
    Check = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.Check").msgclass
    CheckHistory = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.CheckHistory").msgclass
  end
end
