# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hook.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sensu.types.HookConfig" do
    optional :name, :string, 1
    optional :command, :string, 2
    optional :timeout, :uint32, 3
    optional :stdin, :bool, 4
    optional :environment, :string, 5
    optional :organization, :string, 6
  end
  add_message "sensu.types.Hook" do
    optional :config, :message, 1, "sensu.types.HookConfig"
    optional :duration, :double, 2
    optional :executed, :int64, 3
    optional :issued, :int64, 4
    optional :output, :string, 5
    optional :status, :int32, 6
  end
  add_message "sensu.types.HookList" do
    repeated :hooks, :string, 1
    optional :type, :string, 2
  end
end

module Sensu
  module Types
    HookConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.HookConfig").msgclass
    Hook = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.Hook").msgclass
    HookList = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.HookList").msgclass
  end
end
