# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_window.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sensu.types.TimeWindowWhen" do
    optional :days, :message, 1, "sensu.types.TimeWindowDays"
  end
  add_message "sensu.types.TimeWindowDays" do
    repeated :all, :message, 1, "sensu.types.TimeWindowTimeRange"
    repeated :sunday, :message, 2, "sensu.types.TimeWindowTimeRange"
    repeated :monday, :message, 3, "sensu.types.TimeWindowTimeRange"
    repeated :tuesday, :message, 4, "sensu.types.TimeWindowTimeRange"
    repeated :wednesday, :message, 5, "sensu.types.TimeWindowTimeRange"
    repeated :thursday, :message, 6, "sensu.types.TimeWindowTimeRange"
    repeated :friday, :message, 7, "sensu.types.TimeWindowTimeRange"
    repeated :saturday, :message, 8, "sensu.types.TimeWindowTimeRange"
  end
  add_message "sensu.types.TimeWindowTimeRange" do
    optional :begin, :string, 1
    optional :end, :string, 2
  end
end

module Sensu
  module Types
    TimeWindowWhen = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.TimeWindowWhen").msgclass
    TimeWindowDays = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.TimeWindowDays").msgclass
    TimeWindowTimeRange = Google::Protobuf::DescriptorPool.generated_pool.lookup("sensu.types.TimeWindowTimeRange").msgclass
  end
end
